version: '3.9'

services:
  bot:
    build: .
    container_name: isBDaytodayBot
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
